'use strict';
const PDFDocument = require('pdfkit');
const cloudinary = require('../config/cloudinary').cloudinary;
const logger = require('../config/logger');

async function generateOfferLetter(offerData) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 72 });
      const buffers = [];
      doc.on('data', b => buffers.push(b));
      doc.on('error', reject);
      doc.on('end', async () => {
        const pdfBuffer = Buffer.concat(buffers);
        // Upload to Cloudinary
        const result = await new Promise((res, rej) => {
          cloudinary.uploader.upload_stream(
            { folder: 'uniportal/offers', resource_type: 'raw', public_id: `offer-${offerData.offerNumber}`, format: 'pdf' },
            (err, result) => err ? rej(err) : res(result)
          ).end(pdfBuffer);
        });
        resolve(result.secure_url);
      });

      // ── Header ────────────────────────────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 100).fill('#1a56db');
      doc.fillColor('white').fontSize(28).font('Helvetica-Bold').text('UniPortal', 72, 30);
      doc.fontSize(12).font('Helvetica').text('Official Admission Offer Letter', 72, 65);

      doc.moveDown(4);
      doc.fillColor('#111').fontSize(11).font('Helvetica');

      // ── Date & Reference ──────────────────────────────────────────────────
      doc.text(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'right' });
      doc.text(`Offer Reference: ${offerData.offerNumber}`, { align: 'right' });
      doc.moveDown(2);

      // ── Addressee ─────────────────────────────────────────────────────────
      doc.font('Helvetica-Bold').text('Dear ' + offerData.studentName + ',');
      doc.moveDown();
      doc.font('Helvetica').text(
        `We are delighted to inform you that you have been admitted to ${offerData.universityName} for the ` +
        `${offerData.programName} program commencing ${offerData.intake} ${offerData.intakeYear}.`
      );
      doc.moveDown();

      // ── Offer Details Box ─────────────────────────────────────────────────
      const boxTop = doc.y;
      doc.rect(72, boxTop, doc.page.width - 144, 160).fillAndStroke('#f8fafc', '#e2e8f0');
      doc.fillColor('#111');
      doc.font('Helvetica-Bold').text('Admission Details', 90, boxTop + 15);
      doc.font('Helvetica').fontSize(10);
      const details = [
        ['University', offerData.universityName],
        ['Program', offerData.programName],
        ['Degree', offerData.degree],
        ['Intake', `${offerData.intake} ${offerData.intakeYear}`],
        ['Offer Type', offerData.type === 'unconditional' ? 'Unconditional Offer' : 'Conditional Offer'],
        ['Tuition Fee', `USD ${offerData.tuitionFee?.toLocaleString()} per year`],
      ];
      details.forEach(([label, value], i) => {
        doc.text(`${label}: `, 90, boxTop + 40 + i * 18, { continued: true }).font('Helvetica-Bold').text(value).font('Helvetica');
      });

      doc.moveDown(10);

      if (offerData.conditions?.length) {
        doc.font('Helvetica-Bold').text('Conditions of Offer:');
        offerData.conditions.forEach(c => doc.font('Helvetica').text(`• ${c}`));
        doc.moveDown();
      }

      doc.font('Helvetica').text(
        'To accept this offer, please log in to your UniPortal dashboard and click "Accept Offer" before the expiry date.'
      );
      doc.moveDown(2);
      doc.text(`Offer Expires: ${new Date(offerData.expiresAt).toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })}`);
      doc.moveDown(3);
      doc.font('Helvetica-Bold').text('Sincerely,');
      doc.moveDown();
      doc.font('Helvetica').text('Admissions Office');
      doc.text(offerData.universityName);

      // ── Footer ────────────────────────────────────────────────────────────
      doc.rect(0, doc.page.height - 50, doc.page.width, 50).fill('#1a56db');
      doc.fillColor('white').fontSize(9).text('This is an official document generated by UniPortal. Verify at portal.uniportal.io', 0, doc.page.height - 30, { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateOfferLetter };
